#ifndef IPSEC_ERROR_H
#define IPSEC_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum IpsecError {
    IPSEC_OK = 0,
    IPSEC_ERR_INVALID_ARGUMENT,
    IPSEC_ERR_NO_MEMORY,
    IPSEC_ERR_VICI_CONNECT,
    IPSEC_ERR_VICI_TRANSPORT,
    IPSEC_ERR_VICI_PROTOCOL,
    IPSEC_ERR_VICI_TIMEOUT,
    IPSEC_ERR_VICI_COMMAND,
    IPSEC_ERR_DAEMON_NOT_RUNNING,
    IPSEC_ERR_CONNECTION_NOT_FOUND,
    IPSEC_ERR_IKE_FAILED,
    IPSEC_ERR_CHILD_FAILED,
    IPSEC_ERR_NETLINK_SOCKET,
    IPSEC_ERR_NETLINK_SEND,
    IPSEC_ERR_NETLINK_RECV,
    IPSEC_ERR_NETLINK_PARSE,
    IPSEC_ERR_FILE_OPEN,
    IPSEC_ERR_FILE_READ,
    IPSEC_ERR_PERMISSION,
    IPSEC_ERR_BUFFER_TOO_SMALL,
    IPSEC_ERR_NOT_SUPPORTED,
    IPSEC_ERR_INTERNAL
} IpsecError_t;

const char *GetIpsecErrorString(IpsecError_t eError);

#ifdef __cplusplus
}
#endif

#endif
