CROSS_COMPILE ?=
SYSROOT ?=

ifneq ($(filter default undefined,$(origin CC)),)
CC = $(CROSS_COMPILE)gcc
endif
ifneq ($(filter default undefined,$(origin AR)),)
AR = $(CROSS_COMPILE)ar
endif
ifneq ($(filter default undefined,$(origin RANLIB)),)
RANLIB = $(CROSS_COMPILE)ranlib
endif

OUTPUT_DIR ?= ../lib/x86_64
BUILD_DIR ?= obj/x86_64
MKDIR_P ?= mkdir -p
RM_RF ?= rm -rf
RM_F ?= rm -f

CPPFLAGS += -I../include
CPPFLAGS += -Iinternal -Ivici -Ixfrm -Iroute
CFLAGS += -g -O2 -std=c11
CFLAGS += -Wall -Wextra -Wpedantic -Werror
CFLAGS += -fPIC -D_POSIX_C_SOURCE=200809L
LDLIBS += -lpthread

ifneq ($(strip $(SYSROOT)),)
CPPFLAGS += --sysroot=$(SYSROOT)
LDFLAGS += --sysroot=$(SYSROOT)
endif

STATIC_LIBRARY = $(OUTPUT_DIR)/libipsec.a
SHARED_LIBRARY = $(OUTPUT_DIR)/libipsec.so

SRCIPSEC = \
	core/error.c \
	core/ipsec.c \
	core/log.c \
	core/netlink.c \
	core/util.c \
	vici/vici_algorithm.c \
	vici/vici_client.c \
	vici/vici_connection.c \
	vici/vici_credential.c \
	vici/vici_packet.c \
	vici/vici_parser.c \
	vici/vici_sa.c \
	vici/vici_stats.c \
	vici/vici_transport.c \
	xfrm/xfrm_policy.c \
	xfrm/xfrm_state.c \
	xfrm/xfrm_stats.c \
	route/address.c \
	route/interface.c \
	route/route.c

OBJIPSEC = $(patsubst %.c,$(BUILD_DIR)/%.o,$(SRCIPSEC))
DEPFILES = $(OBJIPSEC:.o=.d)

.PHONY: all libraries app clean

all: libraries

libraries: $(STATIC_LIBRARY) $(SHARED_LIBRARY)

app:
	$(MAKE) -C ../apps host CROSS_COMPILE="$(CROSS_COMPILE)" \
		CC="$(CC)" SYSROOT="$(SYSROOT)"

$(STATIC_LIBRARY): $(OBJIPSEC)
	@$(MKDIR_P) $(dir $@)
	$(AR) rcs $@ $^
	$(RANLIB) $@

$(SHARED_LIBRARY): $(OBJIPSEC)
	@$(MKDIR_P) $(dir $@)
	$(CC) -shared $(LDFLAGS) -Wl,-soname,libipsec.so.0 \
		-Wl,--version-script=libipsec.map -o $@ $^ $(LDLIBS)

$(BUILD_DIR)/%.o: %.c
	@$(MKDIR_P) $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -MMD -MP -o $@ -c $<

-include $(DEPFILES)

clean:
	$(RM_RF) $(BUILD_DIR)
	$(RM_F) $(STATIC_LIBRARY) $(SHARED_LIBRARY)
	$(MAKE) -C ../apps clean_host
